# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vika/Downloads/pqcom-1/pqcom/main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(643, 504)
        MainWindow.setBaseSize(QtCore.QSize(640, 504))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.oRecievedData = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oRecievedData.sizePolicy().hasHeightForWidth())
        self.oRecievedData.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        self.oRecievedData.setFont(font)
        self.oRecievedData.setReadOnly(True)
        self.oRecievedData.setObjectName("oRecievedData")
        self.verticalLayout.addWidget(self.oRecievedData)
        self.oSendPane = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oSendPane.sizePolicy().hasHeightForWidth())
        self.oSendPane.setSizePolicy(sizePolicy)
        self.oSendPane.setMinimumSize(QtCore.QSize(0, 0))
        self.oSendPane.setObjectName("oSendPane")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.oSendPane)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sendPlainTextEdit = QtWidgets.QPlainTextEdit(self.oSendPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.sendPlainTextEdit.setSizePolicy(sizePolicy)
        self.sendPlainTextEdit.setMinimumSize(QtCore.QSize(0, 32))
        self.sendPlainTextEdit.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Droid Sans Mono")
        self.sendPlainTextEdit.setFont(font)
        self.sendPlainTextEdit.setObjectName("sendPlainTextEdit")
        self.verticalLayout_2.addWidget(self.sendPlainTextEdit)
        self.oSendControlsPane = QtWidgets.QFrame(self.oSendPane)
        self.oSendControlsPane.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oSendControlsPane.sizePolicy().hasHeightForWidth())
        self.oSendControlsPane.setSizePolicy(sizePolicy)
        self.oSendControlsPane.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.oSendControlsPane.setFrameShadow(QtWidgets.QFrame.Raised)
        self.oSendControlsPane.setObjectName("oSendControlsPane")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.oSendControlsPane)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.normalRadioButton = QtWidgets.QRadioButton(self.oSendControlsPane)
        self.normalRadioButton.setChecked(True)
        self.normalRadioButton.setObjectName("normalRadioButton")
        self.horizontalLayout.addWidget(self.normalRadioButton)
        self.hexRadioButton = QtWidgets.QRadioButton(self.oSendControlsPane)
        self.hexRadioButton.setObjectName("hexRadioButton")
        self.horizontalLayout.addWidget(self.hexRadioButton)
        self.extendRadioButton = QtWidgets.QRadioButton(self.oSendControlsPane)
        self.extendRadioButton.setObjectName("extendRadioButton")
        self.horizontalLayout.addWidget(self.extendRadioButton)
        self.collectButton = QtWidgets.QToolButton(self.oSendControlsPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.collectButton.sizePolicy().hasHeightForWidth())
        self.collectButton.setSizePolicy(sizePolicy)
        self.collectButton.setMinimumSize(QtCore.QSize(0, 20))
        self.collectButton.setText("")
        self.collectButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.collectButton.setObjectName("collectButton")
        self.horizontalLayout.addWidget(self.collectButton)
        self.historyButton = QtWidgets.QPushButton(self.oSendControlsPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.historyButton.sizePolicy().hasHeightForWidth())
        self.historyButton.setSizePolicy(sizePolicy)
        self.historyButton.setObjectName("historyButton")
        self.horizontalLayout.addWidget(self.historyButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.periodSpinBox = QtWidgets.QDoubleSpinBox(self.oSendControlsPane)
        self.periodSpinBox.setEnabled(True)
        self.periodSpinBox.setDecimals(3)
        self.periodSpinBox.setProperty("value", 1.0)
        self.periodSpinBox.setObjectName("periodSpinBox")
        self.horizontalLayout.addWidget(self.periodSpinBox)
        self.repeatCheckBox = QtWidgets.QCheckBox(self.oSendControlsPane)
        self.repeatCheckBox.setObjectName("repeatCheckBox")
        self.horizontalLayout.addWidget(self.repeatCheckBox)
        self.sendButton = QtWidgets.QToolButton(self.oSendControlsPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sendButton.sizePolicy().hasHeightForWidth())
        self.sendButton.setSizePolicy(sizePolicy)
        self.sendButton.setMinimumSize(QtCore.QSize(80, 0))
        self.sendButton.setStyleSheet("")
        self.sendButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.sendButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.sendButton.setAutoRaise(False)
        self.sendButton.setObjectName("sendButton")
        self.horizontalLayout.addWidget(self.sendButton)
        self.verticalLayout_2.addWidget(self.oSendControlsPane)
        self.verticalLayout.addWidget(self.oSendPane)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setMovable(False)
        self.toolBar.setAllowedAreas(QtCore.Qt.TopToolBarArea)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionSetup = QtWidgets.QAction(MainWindow)
        self.actionSetup.setObjectName("actionSetup")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setVisible(False)
        self.actionNew.setObjectName("actionNew")
        self.actionHex = QtWidgets.QAction(MainWindow)
        self.actionHex.setCheckable(True)
        self.actionHex.setVisible(True)
        self.actionHex.setObjectName("actionHex")
        self.actionRun = QtWidgets.QAction(MainWindow)
        self.actionRun.setCheckable(True)
        self.actionRun.setObjectName("actionRun")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionPin = QtWidgets.QAction(MainWindow)
        self.actionPin.setCheckable(True)
        self.actionPin.setObjectName("actionPin")
        self.actionShowSend = QtWidgets.QAction(MainWindow)
        self.actionShowSend.setCheckable(True)
        self.actionShowSend.setObjectName("actionShowSend")
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSetup)
        self.toolBar.addAction(self.actionHex)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addAction(self.actionPin)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionShowSend)
        self.toolBar.addAction(self.actionAbout)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pqcom"))
        self.normalRadioButton.setText(_translate("MainWindow", "Nor&mal"))
        self.hexRadioButton.setText(_translate("MainWindow", "Hex"))
        self.extendRadioButton.setText(_translate("MainWindow", "E&xtended"))
        self.historyButton.setText(_translate("MainWindow", "History"))
        self.periodSpinBox.setSuffix(_translate("MainWindow", "s"))
        self.repeatCheckBox.setText(_translate("MainWindow", "Repeat"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSetup.setText(_translate("MainWindow", "Setup..."))
        self.actionSetup.setIconText(_translate("MainWindow", "Setup..."))
        self.actionSetup.setToolTip(_translate("MainWindow", "Show setup dialog"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionNew.setIconText(_translate("MainWindow", "New..."))
        self.actionNew.setToolTip(_translate("MainWindow", "Run new pqcom and show setup dialog"))
        self.actionHex.setText(_translate("MainWindow", "Hex"))
        self.actionHex.setToolTip(_translate("MainWindow", "View HEX format data"))
        self.actionRun.setText(_translate("MainWindow", "Open"))
        self.actionRun.setToolTip(_translate("MainWindow", "Open com port"))
        self.actionAbout.setText(_translate("MainWindow", "About..."))
        self.actionAbout.setIconText(_translate("MainWindow", "About..."))
        self.actionAbout.setToolTip(_translate("MainWindow", "Show about dialog"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear"))
        self.actionPin.setText(_translate("MainWindow", "Pin"))
        self.actionPin.setToolTip(_translate("MainWindow", "Stay on top"))
        self.actionShowSend.setText(_translate("MainWindow", "Send"))
        self.actionShowSend.setToolTip(_translate("MainWindow", "Show/hide send pane"))

