# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vika/Downloads/pqcom-1/pqcom/setup.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from pqcom.combobox import ComboBox

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(357, 310)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.oBaud = QtWidgets.QComboBox(Dialog)
        self.oBaud.setEditable(True)
        self.oBaud.setObjectName("oBaud")
        self.oBaud.addItem("")
        self.oBaud.addItem("")
        self.oBaud.addItem("")
        self.oBaud.addItem("")
        self.oBaud.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.oBaud)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.oBytebits = QtWidgets.QComboBox(Dialog)
        self.oBytebits.setEditable(False)
        self.oBytebits.setObjectName("oBytebits")
        self.oBytebits.addItem("")
        self.oBytebits.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.oBytebits)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.oStopbits = QtWidgets.QComboBox(Dialog)
        self.oStopbits.setObjectName("oStopbits")
        self.oStopbits.addItem("")
        self.oStopbits.addItem("")
        self.oStopbits.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.oStopbits)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.oParity = QtWidgets.QComboBox(Dialog)
        self.oParity.setObjectName("oParity")
        self.oParity.addItem("")
        self.oParity.addItem("")
        self.oParity.addItem("")
        self.oParity.addItem("")
        self.oParity.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.oParity)
        self.oReconnect = QtWidgets.QCheckBox(Dialog)
        self.oReconnect.setObjectName("oReconnect")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.oReconnect)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setHorizontalSpacing(0)
        self.formLayout_2.setVerticalSpacing(5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.portComboBox = ComboBox(Dialog)
        self.portComboBox.setEditable(True)
        self.portComboBox.setObjectName("portComboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.portComboBox)
        self.oRadioName = QtWidgets.QRadioButton(self.frame)
        self.oRadioName.setChecked(True)
        self.oRadioName.setObjectName("oRadioName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.oRadioName)
        self.oRadioVIDPID = QtWidgets.QRadioButton(self.frame)
        self.oRadioVIDPID.setObjectName("oRadioVIDPID")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.oRadioVIDPID)
        self.oVidpid = QtWidgets.QLineEdit(self.frame)
        self.oVidpid.setObjectName("oVidpid")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.oVidpid)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.frame)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Open)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "pqcom port setup"))
        self.label_2.setText(_translate("Dialog", "Baud Rate"))
        self.oBaud.setItemText(0, _translate("Dialog", "115200"))
        self.oBaud.setItemText(1, _translate("Dialog", "57600"))
        self.oBaud.setItemText(2, _translate("Dialog", "38400"))
        self.oBaud.setItemText(3, _translate("Dialog", "19200"))
        self.oBaud.setItemText(4, _translate("Dialog", "9600"))
        self.label_5.setText(_translate("Dialog", "Data Bits"))
        self.oBytebits.setItemText(0, _translate("Dialog", "8"))
        self.oBytebits.setItemText(1, _translate("Dialog", "7"))
        self.label_3.setText(_translate("Dialog", "Stop Bits"))
        self.oStopbits.setItemText(0, _translate("Dialog", "1"))
        self.oStopbits.setItemText(1, _translate("Dialog", "1.5"))
        self.oStopbits.setItemText(2, _translate("Dialog", "2"))
        self.label_4.setText(_translate("Dialog", "Parity"))
        self.oParity.setItemText(0, _translate("Dialog", "None"))
        self.oParity.setItemText(1, _translate("Dialog", "Even"))
        self.oParity.setItemText(2, _translate("Dialog", "Odd"))
        self.oParity.setItemText(3, _translate("Dialog", "Mark"))
        self.oParity.setItemText(4, _translate("Dialog", "Space"))
        self.oReconnect.setToolTip(_translate("Dialog", "Try to reopen port after disconnect"))
        self.oReconnect.setText(_translate("Dialog", "Reopen"))
        self.oRadioName.setText(_translate("Dialog", "Port Na&me"))
        self.oRadioVIDPID.setToolTip(_translate("Dialog", "List of HEX: VID:PID[, VID:PID...]. Example: 03eb:6124,03eb:2124"))
        self.oRadioVIDPID.setText(_translate("Dialog", "USB &VID:PID"))
        self.oVidpid.setText(_translate("Dialog", "03eb:6124,03eb:2404"))

